image: woohuiren/php-laravel-env:5.3

services:
  - mysql:latest

before_script:
  - bash .gitlab-key-inject.sh # Script injection for SSH keys used for deployments

variables:
  MYSQL_DATABASE: laravel
  MYSQL_ROOT_PASSWORD: secret
  GIT_DEPLOYMENT_REMOTE: staging
  GIT_DEPLOYMENT_BRANCH: master
  SSH_PRIVATE_KEY: somethingsomethingblahblah # Recommended to put into GitLab secret variables instead

stages:
  - build
  - test
  - staging_deploy

build_job:
  stage: build
  script:
    - bash .gitlab-build.sh

test_job:
  stage: test
  script:
    - bash .gitlab-test.sh

stage_job:
  stage: staging_deploy
  script:
    - bash .gitlab-staging-deploy.sh